// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hcfbtbunlqznieubakyf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhjZmJ0YnVubHF6bmlldWJha3lmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDcxMjcyMDAsImV4cCI6MjA2MjcwMzIwMH0.VoK-lWUPkQIAPZr9hUHNUwNcUKASyGE0wec9ZTHFbdY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);